### ISSUE TITLE
How Get PUBG Nickname by SteamID64 ?

### ISSUE THREAD

**Issue by Valor147** [feed4rz/node-battlegrounds#1]
Hello, i need to know if it's possible to get accountID/Nickname PUBG from one user by using his STEAMID64 ?

And if it's possible, how it's work ?

Because i need to link STEAMID64 with an PUBG ACCOUNT to ensure it's the same user.

Best regards, Valor

**Comment by feed4rz** [comment]
Hi, sorry for late answer. I believe it is indeed impossible to do.
