### ISSUE TITLE
PUBG failed look up response?

### ISSUE THREAD

**Issue by aanders50** [feed4rz/node-battlegrounds#5]
Hello, how should I go about getting a failed player look-up? (i.e. a player does not exist or they  spelled their name wrong). 

I tried adding a .catch or viewing the response object from the request but I cannot seem to find the right way to get the error back so I can display it to the user.

```js
let player = await api.getPlayers({ names: [obj.username] });

if (!player || !player[0]) {
    console.log("Could not find player: " + obj.username);
    return;
}
```

Thank you!

**Comment by feed4rz** [comment]
Hey, I am not really working on this package anymore, so the issue might be its not compatible anymore with the current version of API.

You should try just doing http requests to an API itself, documentation can be found here:
https://documentation.pubg.com/en/introduction.html
